### ISSUE TITLE
System.ArgumentOutOfRangeException in buidFeatures method from DecoderTagger class.

### ISSUE THREAD

**Issue by CassioAlan** [zhongkaifu/CRFSharp#10]
Hi, Zhongkai!

I have executed the encode mode succesfully, but running the decode I have the error System.ArgumentOutOfRangeException in _buidFeatures_ method from _DecoderTagger_ class.

```
        for (var cur = 0; cur < word_num; cur++)
        {
            feature_cache_row_size = 0;
            for (int index = 0; index < featureIndex.unigram_templs_.Count; index++)
            {
                var templ = featureIndex.unigram_templs_[index];
                var strFeature = featureIndex.apply_rule(templ, cur, this);
                if (strFeature == "")
                {
                    return Utils.ERROR_EMPTY_FEATURE;
                }
                id = featureIndex.get_id(strFeature);
                if (id != -1)
                {
                    feature_cache_[feature_cache_size][feature_cache_row_size] = id;
                    feature_cache_row_size++;
                }
            }
            feature_cache_[feature_cache_size][feature_cache_row_size] = -1;
            feature_cache_size++;
        }
```

In my case, _word_num_ is 864 and _feature_cache__ has only 200 items. _feature_cache_size_ is increased in each loop, so when _cur_ is 200 I have the OutOfRange exception.

Can you help me?
Thanks!

**Comment by zhongkaifu** [comment]
In decoder, we only set feature_cache_ and feature_cache_size when we initialize feature cache (InitializeFeatureCache()). After that, these two variables won't be changed. So, I feel confused about your description. Could you please provide detailed information about this failure ? such as call stack, input data, model and so on.

**Comment by CassioAlan** [comment]
I ran the following command:
CRFSharpConsole.exe -encode -template template0.template -trainfile train.data -modelfile model0.model

After that, I've tried to apply the model on test data:
CRFSharpConsole.exe -decode -modelfile model0.model -inputfile test.data -outputfile result.data

At this moment occurs the described problem, at line:
`feature_cache_[feature_cache_size][feature_cache_row_size] = id;`

Training, test data and model are attached.

[generated_model.zip](https://github.com/zhongkaifu/CRFSharp/files/524641/generated_model.zip)
[data.zip](https://github.com/zhongkaifu/CRFSharp/files/525738/data.zip)

**Comment by zhongkaifu** [comment]
I have checked your data. The exception was caused by some long sentences. By default, sentence length should be less 100 tokens. If your sentence is longer than 100 tokens,  you can specify "-maxword" in the command. For example: If the longest sentence length is 3000, you could run below command line:

CRFSharpConsole.exe -decode -modelfile model0.model -inputfile test.data -outputfile result.data **-maxword 3000**

**Comment by CassioAlan** [comment]
Thanks a lot!
