### ISSUE TITLE
problem with template file 

### ISSUE THREAD

**Issue by naeimrezaeian** [zhongkaifu/CRFSharp#2]
hanks in advance for this project

i have problem i can not create  template file for my Training corpus , my corpus include two col , Word and POS 
# DELM

اولين                                             ADJ_SUP
سياره                                             N_SING
خارج                                              ADJ_SIM
از                                                P
منظومه                                            N_SING
شمسي                                              ADJ_SIM
ديده                                              ADJ_INO
شد                                                V_PA
.                                                 DELM
# 

please help me to solve problem how create template file for this corpus

**Comment by zhongkaifu** [comment]
Here is an example of template, you can try to use it:

# Unigram

 U01:%x[-1,0]
 U02:%x[0,0]
 U03:%x[1,0]
 U04:%x[-1,0]/%x[0,0]
 U05:%x[0,0]/%x[1,0]
 U06:%x[-1,0]/%x[1,0]
 U07:%x[-1,1]
 U08:%x[0,1]
 U09:%x[1,1]
 U10:%x[-1,1]/%x[0,1]
 U11:%x[0,1]/%x[1,1]
 U12:%x[-1,1]/%x[1,1]
 # Bigram
 B
