### ISSUE TITLE
feature_cache_size

### ISSUE THREAD

**Issue by luvensaitory** [zhongkaifu/CRFSharp#20]
this error happens at DecoderTagger.cs, line 405.
How can I deal with it? Is my data too long?
![image](https://user-images.githubusercontent.com/17849431/44699237-e73ae800-aab5-11e8-928f-b05974e235f8.png)

**Comment by zhongkaifu** [comment]
Probably. Can we dump the sequence when this exception threw ? To resolve this problem, you could either extended feature_cache_ size or convert feate_cache_ from array to list type.

**Comment by luvensaitory** [comment]
索引超出範圍。必須為非負數且小於集合的大小。means that: Index out of range. Must be non-negative and less than the size of the collection.
![image](https://user-images.githubusercontent.com/17849431/44762440-a3a9b200-ab79-11e8-9fc5-fdee0f18a20d.png)
