### ISSUE TITLE
An unhandled exception of type 'System.OutOfMemoryException' occurred in AdvUtils.dll

### ISSUE THREAD

**Issue by My-Khan** [zhongkaifu/CRFSharp#5]
Hello sir, 
when i run the source it start successfully, but at the end of training it generates the following error at the following line of code in modelwriter.cs
 VectorQuantization vq = new VectorQuantization();

An unhandled exception of type 'System.OutOfMemoryException' occurred in AdvUtils.dll

screen shot of the error is 
![image](https://cloud.githubusercontent.com/assets/17508897/14436017/0d7c4d8a-0034-11e6-8298-283b523e765f.png)

![image](https://cloud.githubusercontent.com/assets/17508897/14436026/2690f8ca-0034-11e6-9bce-3634f7de3efe.png)

**Comment by zhongkaifu** [comment]
@My-Khan  this is a bug in vector quantization. As I remembered, I have already fixed this bug by using BigArray. I will take a look.

In order to unblock you, you can specify "-vq 0" in command line, then CRFSharp won't run vector quantization for encode model.

Thanks
Zhongkai Fu

**Comment by My-Khan** [comment]
Many thanks for your prompt reply, its works now.... can you please mention the impact of vector quantization on encode model of CRFSharp. i mean if we run CRFSharp with vector quantization and without vector quantization.. 
Thanks

**Comment by zhongkaifu** [comment]
It affects model size. with vector quantization, the model size is 1/4 of original model size.

**Comment by My-Khan** [comment]
ok sir, you mean it only reduce the size, and have no effect on the final results in decoding mode

**Comment by zhongkaifu** [comment]
The final results diffs should be minor.

**Comment by zhongkaifu** [comment]
I have already updated code to disable "-vq" by default, so you needn't to specify this parameter in command line any more. You can have it by checking out the latest code.

**Comment by My-Khan** [comment]
Bundles of thanks sir, i really appreciate your work.
