### ISSUE TITLE
Probability computation performance

### ISSUE THREAD

**Issue by amironoff** [zhongkaifu/CRFSharp#6]
Hi Zhongkai! Thanks for bringing this project to the community - really useful stuff!

When choosing to calculate prediction variants & their probabilities (vlevel=2), throughput drops around 2.5-3x. I profiled it and found that the bulk of time is spent in Forward-Backward algorithm implementation (calcAlpha/calcBeta methods). 

Do you think there's a way to speed this up?

Cheers,
Andrey

**Comment by zhongkaifu** [comment]
vlevel is used to control how to output result's probabilities. If probabilities are not required in your scenarios, you could set vlevel to 0, and then you will get performance gains. If you want to have probabilities, you may need to optimize existing code, such as converting features weights from double type to integer type, and calculating them by integer type.

**Comment by zhongkaifu** [comment]
Another way is to optimize "log" and "exp" function. Here are some articles maybe helpful for you:
http://www.machinedlearnings.com/2011/06/fast-approximate-logarithm-exponential.html
http://www.quinapalus.com/efunc.html
