### ISSUE TITLE
Build lexical dictionary failed

### ISSUE THREAD

**Issue by danche354** [zhongkaifu/CRFSharp#8]
Hi, Zhongkai,
I have some trouble train my CRF model.
The error message was below:

```
Shrinking feature set [frequency is less than 2]...
Feature size in total : 5483512189
Saving model meta data...Success
Indexing feature set with 0.95 maximum slot usage rate threshold...
Building 5167189 features into index...
Invalidated value -2147483137 at index 2022959
Build lexical dictionary failed.
Failed!
```

Is this because of the memery limit?
I didn't found the information in the CRFCsharp homepage. Can you help me?

Thanks!

**Comment by zhongkaifu** [comment]
That's because your feature size is out of the range of int type, which CRFSharp uses for feature id. Your lexical feature size is 5167189, however, the feature size in total is 5483512189. To resolve this issue:
#1. Reduce the number of rules in template file in order to have less feature size in total.
OR
#2. Update code to change "int" type to "long" type.

**Comment by danche354** [comment]
Thanks for your reply!
I was new to C#, there's another question...
I reviewed your code and found that the error message was occured in 

```
var da = new DoubleArrayTrieBuilder(thread_num_);
        if (da.build(fea, val, 0.95) == false)
        {
            Console.WriteLine("Build lexical dictionary failed.");
            return;
        }
```

but the `DoubleArrayTrieBuilder` and `build` function were referred from AdvUtils.dll, if it means I have to change the dll?

Thanks!

**Comment by zhongkaifu** [comment]
Yes, if you want to modify code to make it support "long" type. AdvUtils is an open source project as well. You can get it from https://github.com/zhongkaifu/AdvUtils

**Comment by danche354** [comment]
hi zhongkai!
Thanks for your previous help! After I check my training data, I figure out the previous problem, but now come across another problem.
After 1 iteration, the console give me a 'out of memory' error, maybe because the data used for the training is too many... 
So is there some parameters or method could control the memory usage?
Thanks again.

**Comment by zhongkaifu** [comment]
It seems that you don't have enough memory for L-BFGS optimization. You can reduce "msize" in below to save memory usage.

File: LBFGS.cs
      public int optimize(double[] x, double C, bool orthant)
        {
            const long msize = 5;
            var size = x.LongLength - 1;
            if (w == null || w.LongLength == 0)
            {

**Comment by danche354** [comment]
if I have changed the msize to 1, and there still exists this problem, is it no way out?

**Comment by zhongkaifu** [comment]
That means your feature set is too large to be kept in memory. Please reduce the number of rules in template file in order to have less feature size in total.

**Comment by danche354** [comment]
Thanks for your patience :-)
